# Generated by Django 5.1.1 on 2024-10-08 15:45

import django.db.models.deletion
import station.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_bus_facility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.create_custom_path
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
